apiVersion: controller.cloudovn.io/v1
kind: RouteTable
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: routetable-sample
spec:
  # TODO(user): Add fields here
