---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - controller.cloudovn.io
  resources:
  - routetables
  - subnets
  - underlaynetworks
  - vpcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controller.cloudovn.io
  resources:
  - routetables/finalizers
  - subnets/finalizers
  - underlaynetworks/finalizers
  - vpcs/finalizers
  verbs:
  - update
- apiGroups:
  - controller.cloudovn.io
  resources:
  - routetables/status
  - subnets/status
  - underlaynetworks/status
  - vpcs/status
  verbs:
  - get
  - patch
  - update
